//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CassVerifyExample.CassVerifyV2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressQuery", Namespace="CASSVerify")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CassVerifyExample.CassVerifyV2.AddressResultRaw))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CassVerifyExample.CassVerifyV2.AddressResultRawLegacy))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CassVerifyExample.CassVerifyV2.AddressResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CassVerifyExample.CassVerifyV2.AddressResultLegacy))]
    public partial class AddressQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResultRaw", Namespace="CASSVerify")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CassVerifyExample.CassVerifyV2.AddressResultRawLegacy))]
    public partial class AddressResultRaw : CassVerifyExample.CassVerifyV2.AddressQuery {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPVDeliveryPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPVFlagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPVFootNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinalistReturnCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPVDeliveryPoint {
            get {
                return this.DPVDeliveryPointField;
            }
            set {
                if ((object.ReferenceEquals(this.DPVDeliveryPointField, value) != true)) {
                    this.DPVDeliveryPointField = value;
                    this.RaisePropertyChanged("DPVDeliveryPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPVFlags {
            get {
                return this.DPVFlagsField;
            }
            set {
                if ((object.ReferenceEquals(this.DPVFlagsField, value) != true)) {
                    this.DPVFlagsField = value;
                    this.RaisePropertyChanged("DPVFlags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DPVFootNote {
            get {
                return this.DPVFootNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.DPVFootNoteField, value) != true)) {
                    this.DPVFootNoteField = value;
                    this.RaisePropertyChanged("DPVFootNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinalistReturnCode {
            get {
                return this.FinalistReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalistReturnCodeField, value) != true)) {
                    this.FinalistReturnCodeField = value;
                    this.RaisePropertyChanged("FinalistReturnCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResultRawLegacy", Namespace="CASSVerify")]
    [System.SerializableAttribute()]
    public partial class AddressResultRawLegacy : CassVerifyExample.CassVerifyV2.AddressResultRaw {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegacyErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegacyErrorCode {
            get {
                return this.LegacyErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LegacyErrorCodeField, value) != true)) {
                    this.LegacyErrorCodeField = value;
                    this.RaisePropertyChanged("LegacyErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResult", Namespace="CASSVerify")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CassVerifyExample.CassVerifyV2.AddressResultLegacy))]
    public partial class AddressResult : CassVerifyExample.CassVerifyV2.AddressQuery {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CassVerifyExample.CassVerifyV2.AddressResultDPV DPVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CassVerifyExample.CassVerifyV2.CASSRefCodesFinalistReturnCode FinalistReturnCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CassVerifyExample.CassVerifyV2.AddressResultDPV DPV {
            get {
                return this.DPVField;
            }
            set {
                if ((object.ReferenceEquals(this.DPVField, value) != true)) {
                    this.DPVField = value;
                    this.RaisePropertyChanged("DPV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CassVerifyExample.CassVerifyV2.CASSRefCodesFinalistReturnCode FinalistReturnCode {
            get {
                return this.FinalistReturnCodeField;
            }
            set {
                if ((this.FinalistReturnCodeField.Equals(value) != true)) {
                    this.FinalistReturnCodeField = value;
                    this.RaisePropertyChanged("FinalistReturnCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResultLegacy", Namespace="CASSVerify")]
    [System.SerializableAttribute()]
    public partial class AddressResultLegacy : CassVerifyExample.CassVerifyV2.AddressResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegacyErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegacyErrorCode {
            get {
                return this.LegacyErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LegacyErrorCodeField, value) != true)) {
                    this.LegacyErrorCodeField = value;
                    this.RaisePropertyChanged("LegacyErrorCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResultDPV", Namespace="CASSVerify")]
    [System.SerializableAttribute()]
    public partial class AddressResultDPV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<CassVerifyExample.CassVerifyV2.CASSRefCodesDPVCMRAFlag> DPVCMRAFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<CassVerifyExample.CassVerifyV2.CASSRefCodesDPVFalsePostiveFlag> DPVFalsePostiveFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<CassVerifyExample.CassVerifyV2.CASSRefCodesDPVFlag> DPVFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CassVerifyExample.CassVerifyV2.CASSRefCodesDPVFootNote[] DPVFootNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<CassVerifyExample.CassVerifyV2.CASSRefCodesDPVCMRAFlag> DPVCMRAFlag {
            get {
                return this.DPVCMRAFlagField;
            }
            set {
                if ((this.DPVCMRAFlagField.Equals(value) != true)) {
                    this.DPVCMRAFlagField = value;
                    this.RaisePropertyChanged("DPVCMRAFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<CassVerifyExample.CassVerifyV2.CASSRefCodesDPVFalsePostiveFlag> DPVFalsePostiveFlag {
            get {
                return this.DPVFalsePostiveFlagField;
            }
            set {
                if ((this.DPVFalsePostiveFlagField.Equals(value) != true)) {
                    this.DPVFalsePostiveFlagField = value;
                    this.RaisePropertyChanged("DPVFalsePostiveFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<CassVerifyExample.CassVerifyV2.CASSRefCodesDPVFlag> DPVFlag {
            get {
                return this.DPVFlagField;
            }
            set {
                if ((this.DPVFlagField.Equals(value) != true)) {
                    this.DPVFlagField = value;
                    this.RaisePropertyChanged("DPVFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CassVerifyExample.CassVerifyV2.CASSRefCodesDPVFootNote[] DPVFootNotes {
            get {
                return this.DPVFootNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.DPVFootNotesField, value) != true)) {
                    this.DPVFootNotesField = value;
                    this.RaisePropertyChanged("DPVFootNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryPoint {
            get {
                return this.DeliveryPointField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointField, value) != true)) {
                    this.DeliveryPointField = value;
                    this.RaisePropertyChanged("DeliveryPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASSRefCodes.FinalistReturnCode", Namespace="http://schemas.datacontract.org/2004/07/CASSVerify.BusinessObjects")]
    public enum CASSRefCodesFinalistReturnCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F0 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F9 = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASSRefCodes.DPVCMRAFlag", Namespace="http://schemas.datacontract.org/2004/07/CASSVerify.BusinessObjects")]
    public enum CASSRefCodesDPVCMRAFlag : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Y = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASSRefCodes.DPVFalsePostiveFlag", Namespace="http://schemas.datacontract.org/2004/07/CASSVerify.BusinessObjects")]
    public enum CASSRefCodesDPVFalsePostiveFlag : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Y = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASSRefCodes.DPVFlag", Namespace="http://schemas.datacontract.org/2004/07/CASSVerify.BusinessObjects")]
    public enum CASSRefCodesDPVFlag : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Y = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        D = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASSRefCodes.DPVFootNote", Namespace="http://schemas.datacontract.org/2004/07/CASSVerify.BusinessObjects")]
    public enum CASSRefCodesDPVFootNote : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        A1 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BB = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        G1 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M1 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M3 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N1 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P1 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P3 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PB = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        R1 = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        R7 = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RR = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        U1 = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CASSVerify", ConfigurationName="CassVerifyV2.CASSVerifyServiceContract")]
    public interface CASSVerifyServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressRaw", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressRawResponse")]
        CassVerifyExample.CassVerifyV2.AddressResultRaw VerifyAddressRaw(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressRaw", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressRawResponse")]
        System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResultRaw> VerifyAddressRawAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressRawLegacy", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressRawLegacyResponse")]
        CassVerifyExample.CassVerifyV2.AddressResultRawLegacy VerifyAddressRawLegacy(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressRawLegacy", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressRawLegacyResponse")]
        System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResultRawLegacy> VerifyAddressRawLegacyAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddress", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressResponse")]
        CassVerifyExample.CassVerifyV2.AddressResult VerifyAddress(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddress", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressResponse")]
        System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResult> VerifyAddressAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressBatch", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressBatchResponse")]
        CassVerifyExample.CassVerifyV2.AddressResult[] VerifyAddressBatch(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery[] addresses);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressBatch", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressBatchResponse")]
        System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResult[]> VerifyAddressBatchAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery[] addresses);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressLegacy", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressLegacyResponse")]
        CassVerifyExample.CassVerifyV2.AddressResultLegacy VerifyAddressLegacy(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressLegacy", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressLegacyResponse")]
        System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResultLegacy> VerifyAddressLegacyAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressDebugDump", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressDebugDumpResponse")]
        string VerifyAddressDebugDump(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/VerifyAddressDebugDump", ReplyAction="CASSVerify/CASSVerifyServiceContract/VerifyAddressDebugDumpResponse")]
        System.Threading.Tasks.Task<string> VerifyAddressDebugDumpAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address);
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/GetVersionInformation", ReplyAction="CASSVerify/CASSVerifyServiceContract/GetVersionInformationResponse")]
        string GetVersionInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="CASSVerify/CASSVerifyServiceContract/GetVersionInformation", ReplyAction="CASSVerify/CASSVerifyServiceContract/GetVersionInformationResponse")]
        System.Threading.Tasks.Task<string> GetVersionInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CASSVerifyServiceContractChannel : CassVerifyExample.CassVerifyV2.CASSVerifyServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CASSVerifyServiceContractClient : System.ServiceModel.ClientBase<CassVerifyExample.CassVerifyV2.CASSVerifyServiceContract>, CassVerifyExample.CassVerifyV2.CASSVerifyServiceContract {
        
        public CASSVerifyServiceContractClient() {
        }
        
        public CASSVerifyServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CASSVerifyServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASSVerifyServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CASSVerifyServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CassVerifyExample.CassVerifyV2.AddressResultRaw VerifyAddressRaw(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressRaw(appKey, address);
        }
        
        public System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResultRaw> VerifyAddressRawAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressRawAsync(appKey, address);
        }
        
        public CassVerifyExample.CassVerifyV2.AddressResultRawLegacy VerifyAddressRawLegacy(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressRawLegacy(appKey, address);
        }
        
        public System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResultRawLegacy> VerifyAddressRawLegacyAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressRawLegacyAsync(appKey, address);
        }
        
        public CassVerifyExample.CassVerifyV2.AddressResult VerifyAddress(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddress(appKey, address);
        }
        
        public System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResult> VerifyAddressAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressAsync(appKey, address);
        }
        
        public CassVerifyExample.CassVerifyV2.AddressResult[] VerifyAddressBatch(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery[] addresses) {
            return base.Channel.VerifyAddressBatch(appKey, addresses);
        }
        
        public System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResult[]> VerifyAddressBatchAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery[] addresses) {
            return base.Channel.VerifyAddressBatchAsync(appKey, addresses);
        }
        
        public CassVerifyExample.CassVerifyV2.AddressResultLegacy VerifyAddressLegacy(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressLegacy(appKey, address);
        }
        
        public System.Threading.Tasks.Task<CassVerifyExample.CassVerifyV2.AddressResultLegacy> VerifyAddressLegacyAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressLegacyAsync(appKey, address);
        }
        
        public string VerifyAddressDebugDump(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressDebugDump(appKey, address);
        }
        
        public System.Threading.Tasks.Task<string> VerifyAddressDebugDumpAsync(string appKey, CassVerifyExample.CassVerifyV2.AddressQuery address) {
            return base.Channel.VerifyAddressDebugDumpAsync(appKey, address);
        }
        
        public string GetVersionInformation() {
            return base.Channel.GetVersionInformation();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionInformationAsync() {
            return base.Channel.GetVersionInformationAsync();
        }
    }
}
