//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CassVerifyExample.CassverifyReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CASSAddress", Namespace="http://state.ak.us")]
    [System.SerializableAttribute()]
    public partial class CASSAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        private bool cassVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returncodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generalRCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string line1 {
            get {
                return this.line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.line1Field, value) != true)) {
                    this.line1Field = value;
                    this.RaisePropertyChanged("line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string line2 {
            get {
                return this.line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.line2Field, value) != true)) {
                    this.line2Field = value;
                    this.RaisePropertyChanged("line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool cassVerified {
            get {
                return this.cassVerifiedField;
            }
            set {
                if ((this.cassVerifiedField.Equals(value) != true)) {
                    this.cassVerifiedField = value;
                    this.RaisePropertyChanged("cassVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string returncode {
            get {
                return this.returncodeField;
            }
            set {
                if ((object.ReferenceEquals(this.returncodeField, value) != true)) {
                    this.returncodeField = value;
                    this.RaisePropertyChanged("returncode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string generalRC {
            get {
                return this.generalRCField;
            }
            set {
                if ((object.ReferenceEquals(this.generalRCField, value) != true)) {
                    this.generalRCField = value;
                    this.RaisePropertyChanged("generalRC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://state.ak.us", ConfigurationName="CassverifyReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name addr from namespace http://state.ak.us is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://state.ak.us/verifyAddress", ReplyAction="*")]
        CassVerifyExample.CassverifyReference.verifyAddressResponse verifyAddress(CassVerifyExample.CassverifyReference.verifyAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://state.ak.us/verifyAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<CassVerifyExample.CassverifyReference.verifyAddressResponse> verifyAddressAsync(CassVerifyExample.CassverifyReference.verifyAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyAddress", Namespace="http://state.ak.us", Order=0)]
        public CassVerifyExample.CassverifyReference.verifyAddressRequestBody Body;
        
        public verifyAddressRequest() {
        }
        
        public verifyAddressRequest(CassVerifyExample.CassverifyReference.verifyAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://state.ak.us")]
    public partial class verifyAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CassVerifyExample.CassverifyReference.CASSAddress addr;
        
        public verifyAddressRequestBody() {
        }
        
        public verifyAddressRequestBody(CassVerifyExample.CassverifyReference.CASSAddress addr) {
            this.addr = addr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyAddressResponse", Namespace="http://state.ak.us", Order=0)]
        public CassVerifyExample.CassverifyReference.verifyAddressResponseBody Body;
        
        public verifyAddressResponse() {
        }
        
        public verifyAddressResponse(CassVerifyExample.CassverifyReference.verifyAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://state.ak.us")]
    public partial class verifyAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CassVerifyExample.CassverifyReference.CASSAddress verifyAddressResult;
        
        public verifyAddressResponseBody() {
        }
        
        public verifyAddressResponseBody(CassVerifyExample.CassverifyReference.CASSAddress verifyAddressResult) {
            this.verifyAddressResult = verifyAddressResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CassVerifyExample.CassverifyReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CassVerifyExample.CassverifyReference.ServiceSoap>, CassVerifyExample.CassverifyReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CassVerifyExample.CassverifyReference.verifyAddressResponse CassVerifyExample.CassverifyReference.ServiceSoap.verifyAddress(CassVerifyExample.CassverifyReference.verifyAddressRequest request) {
            return base.Channel.verifyAddress(request);
        }
        
        public CassVerifyExample.CassverifyReference.CASSAddress verifyAddress(CassVerifyExample.CassverifyReference.CASSAddress addr) {
            CassVerifyExample.CassverifyReference.verifyAddressRequest inValue = new CassVerifyExample.CassverifyReference.verifyAddressRequest();
            inValue.Body = new CassVerifyExample.CassverifyReference.verifyAddressRequestBody();
            inValue.Body.addr = addr;
            CassVerifyExample.CassverifyReference.verifyAddressResponse retVal = ((CassVerifyExample.CassverifyReference.ServiceSoap)(this)).verifyAddress(inValue);
            return retVal.Body.verifyAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CassVerifyExample.CassverifyReference.verifyAddressResponse> CassVerifyExample.CassverifyReference.ServiceSoap.verifyAddressAsync(CassVerifyExample.CassverifyReference.verifyAddressRequest request) {
            return base.Channel.verifyAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<CassVerifyExample.CassverifyReference.verifyAddressResponse> verifyAddressAsync(CassVerifyExample.CassverifyReference.CASSAddress addr) {
            CassVerifyExample.CassverifyReference.verifyAddressRequest inValue = new CassVerifyExample.CassverifyReference.verifyAddressRequest();
            inValue.Body = new CassVerifyExample.CassverifyReference.verifyAddressRequestBody();
            inValue.Body.addr = addr;
            return ((CassVerifyExample.CassverifyReference.ServiceSoap)(this)).verifyAddressAsync(inValue);
        }
    }
}
